//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemAgency.BusinessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JPLATFORMAEntities : DbContext
    {
        public JPLATFORMAEntities()
            : base("name=JPLATFORMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<S_ORGUNITS> S_ORGUNITS { get; set; }
        public virtual DbSet<U_001_ARPS> U_001_ARPS { get; set; }
        public virtual DbSet<U_001_ANLYDIMENSIONS> U_001_ANLYDIMENSIONS { get; set; }
        public virtual DbSet<U_001_AUXCODES> U_001_AUXCODES { get; set; }
        public virtual DbSet<U_001_ITEMS> U_001_ITEMS { get; set; }
        public virtual DbSet<U_001_ANLYDIMTYPES> U_001_ANLYDIMTYPES { get; set; }
    }
}
