//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemAgency.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ntl_ProjectLines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ntl_ProjectLines()
        {
            this.Ntl_ProjectLineSteps = new HashSet<Ntl_ProjectLineSteps>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> VatRate { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> VatTotal { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public Nullable<int> Platform { get; set; }
        public Nullable<bool> Live { get; set; }
        public Nullable<bool> IsAgency { get; set; }
        public Nullable<int> Agency { get; set; }
        public Nullable<int> Influencer { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<double> BuyPrice { get; set; }
    
        public virtual Ntl_Projects Ntl_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ntl_ProjectLineSteps> Ntl_ProjectLineSteps { get; set; }
    }
}
