//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemAgency.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ntl_ProjectLineSteps
    {
        public int Id { get; set; }
        public Nullable<int> ProjectLineId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StepDate { get; set; }
        public string Explanation { get; set; }
        public string Link { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Ntl_ProjectLines Ntl_ProjectLines { get; set; }
    }
}
