//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemAgency.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ntl_ProjectAgreementDocs
    {
        public int Id { get; set; }
        public Nullable<int> ProjectAgreementId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentContentType { get; set; }
        public byte[] DocumentIcon { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
    
        public virtual Ntl_ProjectsAgreement Ntl_ProjectsAgreement { get; set; }
    }
}
