//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemAgency.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ntl_Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ntl_Projects()
        {
            this.Ntl_ProjectLines = new HashSet<Ntl_ProjectLines>();
            this.Ntl_ProjectDocs = new HashSet<Ntl_ProjectDocs>();
        }
    
        public int Id { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> ProjectDate { get; set; }
        public Nullable<int> Company { get; set; }
        public string Origin { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<int> Sector { get; set; }
        public Nullable<int> SubSector { get; set; }
        public string Agency { get; set; }
        public Nullable<int> CustomerName { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ntl_ProjectLines> Ntl_ProjectLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ntl_ProjectDocs> Ntl_ProjectDocs { get; set; }
    }
}
