//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemAgency.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ntl_SubSector
    {
        public int Id { get; set; }
        public Nullable<int> SectorId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Auxcode { get; set; }
    
        public virtual Ntl_Sector Ntl_Sector { get; set; }
    }
}
