//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemAgency.BusinessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEMAGENCYEntities : DbContext
    {
        public TEMAGENCYEntities()
            : base("name=TEMAGENCYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Ntl_Brand> Ntl_Brand { get; set; }
        public virtual DbSet<Ntl_ProjectAgreementDocs> Ntl_ProjectAgreementDocs { get; set; }
        public virtual DbSet<Ntl_ProjectLines> Ntl_ProjectLines { get; set; }
        public virtual DbSet<Ntl_ProjectLineSteps> Ntl_ProjectLineSteps { get; set; }
        public virtual DbSet<Ntl_Projects> Ntl_Projects { get; set; }
        public virtual DbSet<Ntl_Sector> Ntl_Sector { get; set; }
        public virtual DbSet<Ntl_SubSector> Ntl_SubSector { get; set; }
        public virtual DbSet<Ntl_ProjectsAgreement> Ntl_ProjectsAgreement { get; set; }
        public virtual DbSet<Ntl_ProjectDocs> Ntl_ProjectDocs { get; set; }
    }
}
