//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemAgency.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_001_ANLYDIMTYPES
    {
        public int LOGICALREF { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string AUXCODE { get; set; }
        public int BOSTATUS { get; set; }
        public string AUTHCODE { get; set; }
        public int TE_RECSTATUS { get; set; }
        public string TE_LABELS { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public string CREATEDBYNAME { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public Nullable<int> MODIFIEDBY { get; set; }
        public string MODIFIEDBYNAME { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
        public Nullable<int> TE_SUBCOMPANY { get; set; }
        public Nullable<int> TE_WPIID { get; set; }
        public string TE_WFIID { get; set; }
        public Nullable<int> TE_RIGHTS { get; set; }
    }
}
